name: Pull Request CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.19
        uses: actions/setup-node@v2
        with:
          node-version: 14.19
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  backstop:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.19
        uses: actions/setup-node@v2
        with:
          node-version: 14.19
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:local
      - name: Backstop
        run: npm run backstop:test -- --needs-server
      - name: Archive backstop results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: backstop-report
          path: |
            backstop_data/html_report
            backstop_data/reference
            backstop_data/tests
          retention-days: 5
