name: Pull Request CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.15
        uses: actions/setup-node@v3
        with:
          node-version: 16.15
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  backstop:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.15
        uses: actions/setup-node@v3
        with:
          node-version: 16.15
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:local
      - name: Backstop
        run: npm run backstop:test -- --needs-server
      - name: Archive backstop results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: backstop-report
          path: |
            backstop_data/html_report
            backstop_data/reference
            backstop_data/tests
          retention-days: 5
